import { afterEach, expect, it, vi } from 'vitest';
import { sceneLoop } from './lifecycle';
import { createRobinPlayback } from './christmas/robin-playback';
import { createBird, type Scene } from './christmas/robin';
afterEach(() => vi.unstubAllGlobals());
it('keeps one loop through invalidation, reduced motion, backgrounding and teardown', () => {
  const frames = new Map<number, FrameRequestCallback>();
  let id = 0, preference: () => void = () => {}, visibility: () => void = () => {};
  const removeMedia = vi.fn(), removeVisibility = vi.fn();
  const media = { matches: false, addEventListener: (_: string, f: () => void) => { preference = f; }, removeEventListener: removeMedia };
  const doc = { hidden: false, addEventListener: (_: string, f: () => void) => { visibility = f; }, removeEventListener: removeVisibility };
  vi.stubGlobal('matchMedia', () => media);
  vi.stubGlobal('document', doc);
  vi.stubGlobal('requestAnimationFrame', (f: FrameRequestCallback) => { frames.set(++id, f); return id; });
  vi.stubGlobal('cancelAnimationFrame', (i: number) => frames.delete(i));
  const draw = vi.fn(), reset = vi.fn();
  const loop = sceneLoop(draw, reset);
  const run = (now: number) => { const [i, f] = [...frames][0]; frames.delete(i); f(now); };
  loop.invalidate(); loop.invalidate();
  expect(frames.size).toBe(1);
  run(1); expect(frames.size).toBe(1);
  media.matches = true; preference(); preference();
  expect(frames.size).toBe(1);
  run(2); expect(draw).toHaveBeenLastCalledWith(2, true); expect(frames.size).toBe(0);
  doc.hidden = true; visibility(); loop.invalidate(); expect(frames.size).toBe(0);
  doc.hidden = false; visibility(); run(10000); expect(frames.size).toBe(0);
  media.matches = false; preference(); run(10001); expect(frames.size).toBe(1);
  const stale = [...frames.values()][0];
  loop.stop(); stale(10002); loop.invalidate();
  expect(frames.size).toBe(0);
  expect(reset).toHaveBeenCalledTimes(5);
  expect(removeMedia).toHaveBeenCalledOnce(); expect(removeVisibility).toHaveBeenCalledOnce();
});

it('resumes articulation from a new neutral epoch after reduced motion', () => {
  const callbacks = new Map<number, FrameRequestCallback>();
  let id = 0, preference = () => {}, now = 50000;
  const media = { matches: true, addEventListener: (_: string, f: () => void) => { preference = f; }, removeEventListener: () => {} };
  vi.stubGlobal('matchMedia', () => media);
  vi.stubGlobal('document', { hidden: false, addEventListener: () => {}, removeEventListener: () => {} });
  vi.stubGlobal('requestAnimationFrame', (f: FrameRequestCallback) => { callbacks.set(++id, f); return id; });
  vi.stubGlobal('cancelAnimationFrame', (i: number) => callbacks.delete(i));
  const scene: Scene = { floors: new Map([[1, { left: 100, right: 500, y: 200, base: 300, room: 100, headroom: Infinity }]]), obstacles: [], width: 800, height: 600 };
  const bird = createBird(scene, 0, () => .5), player = createRobinPlayback();
  let rendered = player.pose(bird, now, true);
  const loop = sceneLoop((_time, reduced) => { rendered = player.pose(bird, now, reduced); }, player.reset);
  const draw = () => {
    const [key, callback] = [...callbacks][0]; callbacks.delete(key); callback(now);
  };
  draw(); expect(rendered.breathing).toBe(0);
  media.matches = false; preference(); preference();
  expect(callbacks.size).toBe(1);
  now = 100000; draw(); expect(rendered.breathing).toBe(0);
  now += 1600; draw(); expect(rendered.breathing).toBeGreaterThan(.9);
  media.matches = true; preference(); draw(); expect(rendered.breathing).toBe(0);
  expect(callbacks.size).toBe(0);
  loop.stop(); expect(callbacks.size).toBe(0);
});
