import { afterEach, expect, it, vi } from 'vitest';
import { sceneLoop } from './lifecycle';
afterEach(() => vi.unstubAllGlobals());
it('keeps one loop through invalidation, reduced motion, backgrounding and teardown', () => {
  const frames = new Map<number, FrameRequestCallback>();
  let id = 0, preference: () => void = () => {}, visibility: () => void = () => {};
  const removeMedia = vi.fn(), removeVisibility = vi.fn();
  const media = { matches: false, addEventListener: (_: string, f: () => void) => { preference = f; }, removeEventListener: removeMedia };
  const doc = { hidden: false, addEventListener: (_: string, f: () => void) => { visibility = f; }, removeEventListener: removeVisibility };
  vi.stubGlobal('matchMedia', () => media);
  vi.stubGlobal('document', doc);
  vi.stubGlobal('requestAnimationFrame', (f: FrameRequestCallback) => { frames.set(++id, f); return id; });
  vi.stubGlobal('cancelAnimationFrame', (i: number) => frames.delete(i));
  const draw = vi.fn(), reset = vi.fn();
  const loop = sceneLoop(draw, reset);
  const run = (now: number) => { const [i, f] = [...frames][0]; frames.delete(i); f(now); };
  loop.invalidate(); loop.invalidate();
  expect(frames.size).toBe(1);
  run(1); expect(frames.size).toBe(1);
  media.matches = true; preference(); preference();
  expect(frames.size).toBe(1);
  run(2); expect(draw).toHaveBeenLastCalledWith(2, true); expect(frames.size).toBe(0);
  doc.hidden = true; visibility(); loop.invalidate(); expect(frames.size).toBe(0);
  doc.hidden = false; visibility(); run(10000); expect(frames.size).toBe(0);
  media.matches = false; preference(); run(10001); expect(frames.size).toBe(1);
  const stale = [...frames.values()][0];
  loop.stop(); stale(10002); loop.invalidate();
  expect(frames.size).toBe(0);
  expect(reset).toHaveBeenCalledTimes(5);
  expect(removeMedia).toHaveBeenCalledOnce(); expect(removeVisibility).toHaveBeenCalledOnce();
});
